### ISSUE TITLE
White page with NGINX server

### ISSUE THREAD

**Issue by MasterIO02** [robiso/wondercms#184]
Hi all, I recently tried to update WonderCMS 2 to WonderCMS 3.0.4.
I installed WCMS 3.0.4 in the root of my Nginx server, did a `chown -R www-data:www-data [folder]`, then I launched the site and got a white page.

It's been many hours that I try to fix this issue, I tried to change the config file, restart the server but nothing works, all I see is a white page.
I'm using PHP 7.3 and Nginx 1.16.1 on Debian 9.

Does anyone encountered this issue, or knows how to resolve it? Thanks :)

**Comment by StephanStanisic** [comment]
Hi @MasterIO02,

Did you properly copy the `.htaccess` file? It is hidden most of the time and when it's missing could lead to some weird problems.

Could you send us your nginx server config? Without it we can't really see if there may be a problem there.

**Comment by slavenstancic** [comment]
Hi @MasterIO02,

can you please enable display php errors; in php.ini set `display_errors = on` . Then you should be able to see the error instead of white page. Or you can check the nginx log for the error, usually it is in `/var/log/nginx/error.log`.
Then you can paste the error here. Also you can add the nginx server config here.

@StephanStanisic .htaccess is only for apache servers. On nginx should not be included as it is not in use.

**Comment by MasterIO02** [comment]
Thanks for replying. 
Here's the error.log of Nginx : 
[error.log](https://github.com/robiso/wondercms/files/4127992/error.log)

It seems that it can't load the WCMS theme.
The others errors like the forbid ones or summernote (not sure why) is when I tested my old backup of WCMS.

Here's my Nginx config : 
[conf.txt](https://github.com/robiso/wondercms/files/4127995/conf.txt)

**Comment by MasterIO02** [comment]
And the .htaccess file is present @StephanStanisic

**Comment by StephanStanisic** [comment]
:man_facepalming: of course, .htaccess is only for apache. It's not like I use nginx daily... * cough *

Only problem I can see is the `include fastcgi_params`, I have `snippets/fastcgi-php.conf` in most of my configs as path there. 

Does php load correctly? Aka can you create a file with `<?php echo phpinfo();` to see if it works?

**Comment by StephanStanisic** [comment]
Do you have the short php tags enabled? (`<?` instead of `<?php`)

(I didn't see the error log)

**Comment by slavenstancic** [comment]
@MasterIO02 you don't have `short_open_tag` enabled in php.ini as @StephanStanisic mentioned.

As we've already fixed this issue, you just need to update default template from wcms repository (manually in this case).

**Comment by MasterIO02** [comment]
I turned on `short_open_tag` but the issue is still the same (I restarted the server after modifying php.ini). What do you mean by updating the template? Updating the Nginx config file or the WCMS theme template?
I created the `<?php echo phpinfo();` file and it does not work. However, with my old WonderCMS config file it works. Here it is : [oldconf.txt](https://github.com/robiso/wondercms/files/4128713/oldconf.txt)

**Comment by slavenstancic** [comment]
Can you try updating your themes default folder with this files https://github.com/robiso/wondercms/tree/master/themes/default

**Comment by robiso** [comment]
@MasterIO02, as suggested above, we recently had a bug in the default theme which rendered white pages for some users that didn't support shorts tags.

If updating the default theme doesn't help, we can debug from the onwards.

@StephanStanisic & @slavenstancic, thanks for helping out. 🚀

**Comment by MasterIO02** [comment]
I replaced the old theme by the new one. At first it was not working.
I think the fact that the `index index.php` was in the PHP location is because it was the old WCMS template config before the major 3.0 update.
I copied some of the lines of my old config file and it seems that the 
`fastcgi_param SCRIPT_FILENAME [PATH TO THE WEBSITE]$fastcgi_script_name;` line is making the site work, with or without the `index index.php` on the location settings.

I tried the majority of the website and it works as intended!

I hope this issue will not reproduce in the future.
Thanks a lot @StephanStanisic , @slavenstancic and @robiso for helping me figuring out this issue.

**Comment by StephanStanisic** [comment]
I think this could be the case because of the missing `include snippets/fastcgi-php.conf` that I mentioned earlier. 

The file `snippets/fastcgi-php.conf` includes the `fastcgi.conf` file that contains a lot of `fastcgi_param` lines. (including the `SCRIPT_NAME` you where talking about).

A few of the plugins I've build and the `$Wcms->url()` function is highly dependent on these variables so I would suggest adding the following line to your nginx config: (in the location block)
```
include snippets/fastcgi-php.conf;
```

**Comment by robiso** [comment]
@MasterIO02 thanks for giving out enough data and helping stream down possible causes.
@slavenstancic @StephanStanisic awesome work as always 👌

**Comment by robiso** [comment]
Closing issue, please feel free to continue the discussion,
